[package]
name = "data_analises"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.19.0"
tokio = { version = "1", features = ["full"] }
reqwest = "0.12.4"
anyhow = "1.0.84"